/**
 * Word lists for Codenames
 * Supports Spanish and English
 */

export const WORDS_ES = [
  "Árbol", "Avión", "Agua", "Aire", "Ancla", "Anillo", "Antorcha", "Araña", "Arco", "Arena",
  "Asalto", "Astro", "Atlas", "Atleta", "Auto", "Azúcar", "Bala", "Banco", "Banda", "Baño",
  "Barba", "Barco", "Barra", "Base", "Batería", "Bebé", "Beso", "Bicho", "Billete", "Blanco",
  "Bloque", "Boca", "Bola", "Bolsa", "Bomba", "Bota", "Botella", "Botón", "Brazo", "Bruja",
  "Caballo", "Cabeza", "Cabo", "Cactus", "Cadena", "Caja", "Cama", "Cámara", "Campo", "Canal",
  "Canguro", "Canto", "Caña", "Capa", "Capital", "Capitán", "Cara", "Caravana", "Cárcel", "Cardo",
  "Carga", "Carro", "Carta", "Casco", "Casino", "Castillo", "Cebra", "Célula", "Cena", "Centro",
  "Cerca", "Cerdo", "Cero", "Césped", "Chapa", "Cheque", "China", "Chocolate", "Chorro", "Cielo",
  "Cien", "Cinta", "Cinturón", "Círculo", "Ciudad", "Clase", "Clavo", "Clip", "Club", "Coche",
  "Cocina", "Coco", "Código", "Cola", "Columna", "Cometa", "Compás", "Concierto", "Conejo", "Copa",
  "Corazón", "Corcho", "Cordón", "Corona", "Corredor", "Correo", "Corte", "Corteza", "Cortina", "Costa",
  "Cresta", "Cromo", "Cruz", "Cuadro", "Cuarto", "Cubierta", "Cubo", "Cuello", "Cuerda", "Cuerno",
  "Cuerpo", "Cueva", "Cuna", "Dado", "Dama", "Dedo", "Delfín", "Derecha", "Desierto", "Día",
  "Diamante", "Diana", "Diario", "Diente", "Dinosaurio", "Disco", "Doctor", "Dólar", "Domingo", "Dragón",
  "Duna", "Eje", "Elefante", "Embajador", "Enano", "Enchufe", "Energía", "Enfermedad", "Enfermera", "Enlace",
  "Escala", "Escoba", "Escorpión", "Escudo", "Escuela", "Espada", "Espalda", "Espejo", "Espía", "Espina",
  "Espíritu", "Esposa", "Estación", "Estado", "Este", "Estrella", "Estudio", "Etiqueta", "Europa", "Explosivo",
  "Extraterrestre", "Fábrica", "Falda", "Fantasma", "Faro", "Ficha", "Fiesta", "Figura", "Fila", "Final",
  "Flauta", "Flecha", "Flor", "Foco", "Fondo", "Forma", "Forro", "Fosa", "Francia", "Frente",
  "Fresa", "Fuego", "Fuente", "Fuerza", "Funda", "Fusil", "Gafas", "Gallo", "Gancho", "Gato",
  "Genio", "Gigante", "Globo", "Golfo", "Goma", "Gorra", "Gota", "Grado", "Granada", "Granja",
  "Grasa", "Grifo", "Grillo", "Grito", "Grupo", "Guante", "Guardia", "Guerra", "Guía", "Guitarra",
  "Hacha", "Hada", "Harina", "Helado", "Helicóptero", "Hielo", "Hierba", "Hierro", "Hígado", "Hijo",
  "Hilo", "Hoja", "Hombre", "Hormiga", "Hospital", "Hotel", "Hueso", "Huevo", "Humo", "Huracán",
  "Imán", "Imperio", "Indio", "Infierno", "Inglaterra", "Insecto", "Instrumento", "Isla", "Jabón", "Jamón",
  "Jardín", "Jarra", "Jefe", "Jirafa", "Juego", "Jueves", "Juez", "Jugo", "Juguete", "Junta",
  "Júpiter", "Kilo", "Labio", "Laboratorio", "Lado", "Ladrillo", "Ladrón", "Lago", "Lámpara", "Lana",
  "Lanza", "Lápiz", "Lata", "Látigo", "Lazo", "Leche", "Lecho", "Lengua", "León", "Letra",
  "Ley", "Libertad", "Libra", "Libro", "Lienzo", "Liga", "Limón", "Línea", "Lirio", "Lista",
  "Llama", "Llave", "Lobo", "Loco", "Lona", "Loro", "Lote", "Lucha", "Luna", "Luz",
  "Macho", "Madera", "Madre", "Magia", "Mago", "Maíz", "Maleta", "Malla", "Mano", "Manta",
  "Manzana", "Mañana", "Mapa", "Máquina", "Mar", "Marca", "Marcha", "Marfil", "Margarita", "Martillo",
  "Marzo", "Masa", "Máscara", "Mazo", "Media", "Médico", "Medida", "Medio", "Mejilla", "Melón",
  "Memoria", "Mente", "Mercado", "Merengue", "Mes", "Mesa", "Metal", "Metro", "México", "Mezcla",
  "Miedo", "Miel", "Mierda", "Milla", "Mina", "Minuto", "Misa", "Misión", "Mito", "Mochila",
  "Modelo", "Modo", "Moho", "Molde", "Mole", "Muelle", "Muerte", "Muestra", "Mujer", "Mundo",
  "Muñeca", "Muro", "Museo", "Música", "Nación", "Nada", "Nadador", "Naranja", "Nariz", "Naturaleza",
  "Nave", "Navidad", "Negro", "Nervio", "Nido", "Niebla", "Nieve", "Niño", "Noche", "Nombre",
  "Norte", "Nota", "Nube", "Nudo", "Nueva York", "Número", "Oasis", "Objeto", "Océano", "Ocho",
  "Ojo", "Ola", "Olivo", "Olla", "Ombligo", "Onda", "Ópera", "Orden", "Oreja", "Oro",
  "Oruga", "Oso", "Oveja", "Óxido", "Padre", "Página", "Paja", "Pájaro", "Pala", "Palacio",
  "Palma", "Palo", "Paloma", "Pan", "Pantalón", "Pantalla", "Paño", "Papa", "Papel", "Parada",
  "Paraguas", "Paraíso", "Pared", "Parque", "Parte", "Pasaje", "Paso", "Pasta", "Pastel", "Pata",
  "Patio", "Pato", "Pavo", "Paz", "Pecho", "Pecado", "Pegamento", "Peine", "Película", "Pelota",
  "Pelo", "Pena", "Péndulo", "Pensamiento", "Peón", "Pepino", "Pera", "Perla", "Perro", "Persona",
  "Pesa", "Pescado", "Pestaña", "Pez", "Piano", "Pie", "Piedra", "Piel", "Pierna", "Pieza",
  "Pila", "Piloto", "Pimienta", "Pino", "Pintura", "Pinza", "Piña", "Pipa", "Pirámide", "Pirata",
  "Piso", "Pista", "Pistola", "Pizarra", "Placa", "Plan", "Plancha", "Planeta", "Planta", "Plástico",
  "Plata", "Plátano", "Plato", "Playa", "Plaza", "Plomo", "Pluma", "Pobre", "Poder", "Poeta",
  "Policía", "Pollo", "Polvo", "Pompa", "Puente", "Puerto", "Puesto", "Pulga", "Pulmón", "Pulpo",
  "Punta", "Punto", "Puño", "Radio", "Raíz", "Rama", "Rana", "Rata", "Rayo", "Red",
  "Regla", "Reina", "Reloj", "Remo", "Resorte", "Rey", "Río", "Roca", "Rosa", "Rueda",
  "Ruido", "Sable", "Saco", "Sal", "Salida", "Salsa", "Salto", "Sangre", "Sapo", "Satélite",
  "Seda", "Selva", "Sello", "Semilla", "Senado", "Señal", "Serie", "Serpiente", "Sierra", "Silla",
  "Sirena", "Sobre", "Sol", "Sombra", "Sonda", "Sopa", "Sordo", "Suave", "Suelo", "Sueño",
  "Suerte", "Suiza", "Tabla", "Taco", "Tacto", "Taladro", "Talón", "Tanque", "Tapa", "Tapón",
  "Tarde", "Tarea", "Tarjeta", "Tarta", "Taza", "Teatro", "Techo", "Teclado", "Tela", "Teléfono",
  "Telescopio", "Tema", "Templo", "Tenis", "Tensión", "Tierra", "Tigre", "Tijeras", "Tinta", "Tío",
  "Tira", "Tiro", "Título", "Tiza", "Toalla", "Tobillo", "Toga", "Tomate", "Tono", "Tope",
  "Torre", "Tortuga", "Trabajo", "Traje", "Trampa", "Tren", "Triángulo", "Trigo", "Trono", "Tropa",
  "Trueno", "Tubo", "Túnel", "Turno", "Uña", "Universo", "Uva", "Vaca", "Vacío", "Vagón",
  "Vaina", "Valle", "Vampiro", "Vara", "Vaso", "Vela", "Veneno", "Venta", "Ventana", "Venus",
  "Verano", "Verde", "Vestido", "Viaje", "Vida", "Vidrio", "Viento", "Vientre", "Vino", "Violín",
  "Vista", "Viuda", "Vuelo", "Voz", "Yate", "Yema", "Yodo", "Yugo", "Zanahoria", "Zapato"
];

export const WORDS_EN = [
  "Apple", "Antarctica", "Air", "Anchor", "Angel", "Arm", "Atlantis", "Australia", "Aztec", "Back",
  "Ball", "Band", "Bank", "Bar", "Bark", "Bat", "Battery", "Beach", "Bear", "Beat",
  "Bed", "Beijing", "Bell", "Belt", "Berlin", "Bermuda", "Berry", "Bill", "Block", "Board",
  "Bolt", "Bomb", "Bond", "Boom", "Boot", "Bottle", "Bow", "Box", "Bridge", "Brush",
  "Buck", "Buffalo", "Bug", "Bugle", "Button", "Calf", "Canada", "Cap", "Capital", "Car",
  "Card", "Carrot", "Casino", "Cast", "Cat", "Cell", "Centaur", "Center", "Chair", "Change",
  "Charge", "Check", "Chest", "Chick", "China", "Chocolate", "Church", "Circle", "Cliff", "Cloak",
  "Club", "Code", "Cold", "Comic", "Compound", "Concert", "Conductor", "Cook", "Copper", "Cotton",
  "Court", "Cover", "Crane", "Crash", "Cricket", "Cross", "Crown", "Cycle", "Czech", "Dance",
  "Date", "Day", "Death", "Deck", "Degree", "Diamond", "Dice", "Dinosaur", "Disease", "Doctor",
  "Dog", "Draft", "Dragon", "Dress", "Drill", "Drink", "Drive", "Drum", "Duck", "Dust",
  "Eagle", "Egypt", "Embassy", "Engine", "England", "Europe", "Eye", "Face", "Fair", "Fall",
  "Fan", "Field", "Fighter", "Figure", "File", "Film", "Fire", "Fish", "Flute", "Fly",
  "Foot", "Force", "Forest", "Fork", "France", "Game", "Gas", "Genius", "Germany", "Ghost",
  "Giant", "Glass", "Glove", "Gold", "Grace", "Grass", "Greece", "Green", "Ground", "Ham",
  "Hand", "Hawk", "Head", "Heart", "Helicopter", "Himalayas", "Hole", "Hollywood", "Honey", "Hood",
  "Hook", "Horn", "Horse", "Horseshoe", "Hospital", "Hotel", "Ice", "Ice Cream", "India", "Iron",
  "Ivory", "Jack", "Jam", "Jet", "Jupiter", "Kangaroo", "Ketchup", "Key", "Kid", "King",
  "Kiwi", "Knife", "Knight", "Knot", "Kung Fu", "Lab", "Lap", "Laser", "Lawyer", "Lead",
  "Lemon", "Leprechaun", "Life", "Light", "Limousine", "Line", "Link", "Lion", "Litter", "Loch Ness",
  "Lock", "Log", "London", "Luck", "Mail", "Mammoth", "Maple", "Marble", "March", "Mass",
  "Match", "Mercury", "Mexico", "Microscope", "Millionaire", "Mine", "Mint", "Missile", "Model", "Mole",
  "Moon", "Moscow", "Mount", "Mouse", "Mouth", "Mug", "Mummy", "Nail", "Needle", "Net",
  "New York", "Night", "Ninja", "Note", "Novel", "Nurse", "Nut", "Octopus", "Oil", "Olive",
  "Olympus", "Opera", "Orange", "Organ", "Palm", "Pan", "Pants", "Paper", "Parachute", "Park",
  "Part", "Pass", "Paste", "Penguin", "Phoenix", "Piano", "Pie", "Pilot", "Pin", "Pipe",
  "Pirate", "Pistol", "Pit", "Plane", "Plastic", "Plate", "Platypus", "Play", "Plot", "Point",
  "Poison", "Pole", "Police", "Pool", "Port", "Post", "Pound", "Press", "Princess", "Pumpkin",
  "Pupil", "Pyramid", "Queen", "Rabbit", "Racket", "Ray", "Revolution", "Ring", "Robin", "Robot",
  "Rock", "Rodeo", "Roller", "Roof", "Root", "Rose", "Roulette", "Round", "Row", "Ruler",
  "Satellite", "Saturn", "Scale", "School", "Scientist", "Scorpion", "Screen", "Scuba Diver", "Seal", "Server",
  "Shadow", "Shakespeare", "Shark", "Ship", "Shoe", "Shop", "Shot", "Show", "Sickle", "Sign",
  "Sink", "Skyscraper", "Slip", "Slug", "Smuggler", "Snow", "Snowman", "Sock", "Soldier", "Soul",
  "Sound", "Space", "Spell", "Spider", "Spike", "Spine", "Spot", "Spring", "Spy", "Square",
  "Stadium", "Staff", "Star", "State", "Stick", "Stock", "Straw", "Stream", "Strike", "Sub",
  "Suit", "Superhero", "Swing", "Switch", "Table", "Tablet", "Tag", "Tail", "Tap", "Teacher",
  "Telescope", "Temple", "Theater", "Thief", "Thumb", "Tick", "Tie", "Time", "Tokyo", "Tooth",
  "Torch", "Tower", "Track", "Train", "Triangle", "Trip", "Trunk", "Tube", "Turkey", "Undertaker",
  "Unicorn", "Vacuum", "Van", "Venus", "Wake", "Wall", "War", "Washer", "Washington", "Watch",
  "Water", "Wave", "Web", "Well", "Whale", "Whip", "Wind", "Witch", "Worm", "Yard"
];
